### ISSUE TITLE
transcrypt use CPython to create *.html

### ISSUE THREAD

**Issue by hoskylucky** [JdeH/Transcrypt#117] opened 2016-09-26 05:41 UTC
hi,I follow documentation to run: transcrypt -r autotest.py, and shows that:

Error: cannot run autotest.py using CPython: No module named 'arguments'

I used pip to install transcrypt.

something wrong?

**Comment by hoskylucky** [comment] 2016-09-26 08:43
I write transcrypt.pth in site-packages, include "transcrypt\\development\\automated_tests\\transcrypt", and it works.

Any other advise?

**Comment by JdeH** [comment] 2016-09-26 09:08
Hi,

Thanks for the feedback!

I've been looking into this and unfortunately I can not reproduce this problem on Linux or Windows.
Clearly something is wrong with the module search path used when the -r switch is on.

The code where the module search path is determined is in the following lines at the top of \_\_main\_\_.py:

```
programDir = os.getcwd () .replace ('\\', '/')
transpilerDir = os.path.dirname (os.path.abspath (__file__)) .replace ('\\', '/')	
modulesDir = '{}/modules'.format (transpilerDir)

# Both CPython and Transcrypt will use all dirs in sys.path as search roots for modules
# CPython will also search relatively from each module, Transcrypt only from the main module

compilerPath = [programDir, modulesDir] + sys.path	# Used by Transcrypt rather than CPython, programDir isn't always part of the path under Linux
sys.path = sys.path	[1:] + [modulesDir]				# Used by CPython, leave out current dir to prevent importing modules root if
```

Could you add the following print statements below the fragment just shown and let me know the result:

```
print (programDir)
print (transpilerDir)
print (modulesDir)
print (compilerPath)
print (sys.path)

```

Maybe then it will become clear what is the problem.

By the way, are you on Windows, Linux or OsX?

Kind regards
Jacques de Hooge

**Comment by hoskylucky** [comment] 2016-09-26 09:36
hi, thank you for your response.

I del .pth file, and I add source in __main__.py like this:

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
programDir = os.getcwd () .replace ('\\', '/')
transpilerDir = os.path.dirname (os.path.abspath (__file__)) .replace ('\\', '/')	
modulesDir = '{}/modules'.format (transpilerDir)

# Both CPython and Transcrypt will use all dirs in sys.path as search roots for modules
# CPython will also search relatively from each module, Transcrypt only from the main module

compilerPath = [programDir, modulesDir] + sys.path	# Used by Transcrypt rather than CPython, programDir isn't always part of the path under Linux
sys.path = sys.path	[1:] + [modulesDir]				# Used by CPython, leave out current dir to prevent importing modules root if there's a module by that name
sys.modules.pop ('org', None)						# Unload org from a packages dir, if it's there.

print ('programDir: ', programDir)
print ('transpilerDir: ', transpilerDir)
print ('modulesDir: ', modulesDir)
print ('compilerPath: ', compilerPath)
print ('sys.path: ', sys.path)
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

then I command prompt run "c:\ENV\Lib\site-packages\transcrypt\run_transcrypt.bat -r autotest.py", it outputs this follow:
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
programDir:  C:/ENV/Lib/site-packages/transcrypt/development/automated_tests/transcrypt
transpilerDir:  c:/ENV/Lib/site-packages/transcrypt
modulesDir:  c:/ENV/Lib/site-packages/transcrypt/modules
compilerPath:  ['C:/ENV/Lib/site-packages/transcrypt/development/automated_tests/transcrypt', 'c:/ENV/Lib/site-packages/transcrypt/modules', 'c:\\ENV\\Lib\\site-packages\\transcrypt', 'C:\\ENV\\Scripts\\python35.zip', 'C:\\ENV\\DLLs', 'C:\\ENV\\lib', 'C:\\ENV\\Scripts', 'c:\\users\\hosky\\appdata\\local\\programs\\python\\python35\\Lib', 'c:\\users\\hosky\\appdata\\local\\programs\\python\\python35\\DLLs', 'C:\\ENV', 'C:\\ENV\\lib\\site-packages']
sys.path:  ['C:\\ENV\\Scripts\\python35.zip', 'C:\\ENV\\DLLs', 'C:\\ENV\\lib', 'C:\\ENV\\Scripts', 'c:\\users\\hosky\\appdata\\local\\programs\\python\\python35\\Lib', 'c:\\users\\hosky\\appdata\\local\\programs\\python\\python35\\DLLs', 'C:\\ENV', 'C:\\ENV\\lib\\site-packages', 'c:/ENV/Lib/site-packages/transcrypt/modules']
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.222
Copyright (C) Geatec Engineering. License: Apache 2.0

Error: cannot run autotest.py using CPython: No module named 'arguments'

Aborted
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////

After that, I recovery transcrypt.pth in site-packages, and it works.

And I use Windows.

Hope that would be useful.

**Comment by JdeH** [comment] 2016-09-26 12:09
Hi,

I've committed a fix for this and also uploaded it to PyPi (3.5.226). However since I cannot reproduce the error here, could you tell me if this works for you.

KR
J

**Comment by hoskylucky** [comment] 2016-09-26 13:13
Hi,

I've added your fix, and output this:

> programDir:  C:/ENV/Lib/site-packages/transcrypt/development/automated_tests/transcrypt
transpilerDir:  c:/ENV/Lib/site-packages/transcrypt
modulesDir:  c:/ENV/Lib/site-packages/transcrypt/modules
compilerPath:  ['C:/ENV/Lib/site-packages/transcrypt/development/automated_tests/transcrypt', 'c:/ENV/Lib/site-packages/transcrypt/modules', 'c:\\ENV\\Lib\\site-packages\\transcrypt', 'C:\\ENV\\Scripts\\python35.zip', 'C:\\ENV\\DLLs', 'C:\\ENV\\lib', 'C:\\ENV\\Scripts', 'c:\\users\\hosky\\appdata\\local\\programs\\python\\python35\\Lib', 'c:\\users\\hosky\\appdata\\local\\programs\\python\\python35\\DLLs', 'C:\\ENV', 'C:\\ENV\\lib\\site-packages']
sys.path:  ['c:\\ENV\\Lib\\site-packages\\transcrypt', 'C:\\ENV\\Scripts\\python35.zip', 'C:\\ENV\\DLLs', 'C:\\ENV\\lib', 'C:\\ENV\\Scripts', 'c:\\users\\hosky\\appdata\\local\\programs\\python\\python35\\Lib', 'c:\\users\\hosky\\appdata\\local\\programs\\python\\python35\\DLLs', 'C:\\ENV', 'C:\\ENV\\lib\\site-packages', 'c:/ENV/Lib/site-packages/transcrypt/modules']
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.222
Copyright (C) Geatec Engineering. License: Apache 2.0
Error: cannot run autotest.py using CPython: No module named 'arguments'

It still not work.

And I change code like this:

> sys.path += [modulesDir, programDir]

Output this:

> programDir:  C:/ENV/Lib/site-packages/transcrypt/development/automated_tests/transcrypt
transpilerDir:  c:/ENV/Lib/site-packages/transcrypt
modulesDir:  c:/ENV/Lib/site-packages/transcrypt/modules
compilerPath:  ['C:/ENV/Lib/site-packages/transcrypt/development/automated_tests/transcrypt', 'c:/ENV/Lib/site-packages/transcrypt/modules', 'c:\\ENV\\Lib\\site-packages\\transcrypt', 'C:\\ENV\\Scripts\\python35.zip', 'C:\\ENV\\DLLs', 'C:\\ENV\\lib', 'C:\\ENV\\Scripts', 'c:\\users\\hosky\\appdata\\local\\programs\\python\\python35\\Lib', 'c:\\users\\hosky\\appdata\\local\\programs\\python\\python35\\DLLs', 'C:\\ENV', 'C:\\ENV\\lib\\site-packages']
sys.path:  ['c:\\ENV\\Lib\\site-packages\\transcrypt', 'C:\\ENV\\Scripts\\python35.zip', 'C:\\ENV\\DLLs', 'C:\\ENV\\lib', 'C:\\ENV\\Scripts', 'c:\\users\\hosky\\appdata\\local\\programs\\python\\python35\\Lib', 'c:\\users\\hosky\\appdata\\local\\programs\\python\\python35\\DLLs', 'C:\\ENV', 'C:\\ENV\\lib\\site-packages', 'c:/ENV/Lib/site-packages/transcrypt/modules', 'C:/ENV/Lib/site-packages/transcrypt/development/automated_tests/transcrypt']
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.5.222
Copyright (C) Geatec Engineering. License: Apache 2.0
Error: cannot run autotest.py using CPython: module 'modules' has no attribute 'run'

Then I code like this:

> sys.path = sys.path	[1:] + [modulesDir, programDir]

It works finally.

It still has a bug that if I run command like: 

> (ENV) C:\ENV\Lib\site-packages\transcrypt\development\automated_tests>c:\ENV\Lib\site-packages\transcrypt\run_transcrypt.bat -r transcrypt\autotest.py

It also does not work.

Hope useful.

**Comment by JdeH** [comment] 2016-09-26 13:29
Hi

Great that you found a solution for the first problem. I'll have to test it in different installations, but if it works I'll integrate it in the distro.

About the new problem: you can only run transcrypt from the directory where your sourcefile is. So not from the directory above that. So you'll have to run it in the directory where autotest.py is (or make that your current directory temporarilily.

KR
J

**Closed** 2016-09-26 15:59 UTC
Labels: bug
