### ISSUE TITLE
install as python setup.py install --user seems to fail fyi

### ISSUE THREAD

**Issue by c-h-u-c-k** [JdeH/Transcrypt#111] opened 2016-09-07 05:37 UTC
#python 2.7
user@box $ transcrypt --help
Traceback (most recent call last):
  File "/home/user/.local/bin/transcrypt", line 9, in <module>
    load_entry_point('Transcrypt==3.5.220', 'console_scripts', 'transcrypt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
ImportError: No module named transcrypt.__main__

#python 3.4
user@box $ transcrypt --help
Traceback (most recent call last):
  File "/home/user/.local/bin/transcrypt", line 9, in <module>
    load_entry_point('Transcrypt==3.5.220', 'console_scripts', 'transcrypt')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/home/chuck/.local/lib/python3.4/site-packages/Transcrypt-3.5.220-py3.4.egg/transcrypt/__main__.py", line 35, in <module>
    from org.transcrypt import utils
  File "/home/user/.local/lib/python3.4/site-packages/Transcrypt-3.5.220-py3.4.egg/transcrypt/modules/org/transcrypt/utils.py", line 143
    '''.format (exception.__class__, *inspect.stack () [1][1:-1], kwargs, result))
                                                                  ^
SyntaxError: only named arguments may follow *expression

**Comment by JdeH** [comment] 2016-09-07 05:46
Hi,

The problem is you attempt to install under Python 3.5.
Transcrypt requires Python 3.5.
Hope this helps.

Kind regards
Jacques

**Comment by c-h-u-c-k** [comment] 2016-09-07 06:03
Makes sense, I didn't realise it required 3.5. Thanks

**Comment by JdeH** [comment] 2016-09-10 07:11
I'll close this for now. Feel free to reopen if there's still a problem.

KR
Jacques

**Closed by JdeH** 2016-09-10 07:11 UTC
Labels: question
