### ISSUE TITLE
Sourcemaps ?

### ISSUE THREAD

**Issue by ihph** [JdeH/Transcrypt#104] opened 2016-08-28 13:22 UTC
Can't get sourcemaps to run...files seem to be missing from master ?

```
[Errno 2] No such file or directory:
lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/__javascript__/extra/sourcemap/org.transcrypt.__base__.mod.js.map'Traceback
```

**Comment by JdeH** [comment] 2016-08-30 17:55
Thanks!

I'll look into this a.s.a.p.

**Comment by miguelgrinberg** [comment] 2016-09-06 06:35
Having the same problem. I have `Transcrypt==3.5.219` installed.

**Comment by JdeH** [comment] 2016-09-06 08:22
Hi,

I think I found the cause of this. If previously a compilation was done without the -m option, __base__.mod.j willstill  be up to date (since the source didn't change). So when recompiling with the -m option, Transcrypt wrongfully sees no reason to recompile and hence doesn't generate a partial map for that module. If then later on it tries to assemble the overall map, it misses __base__.mod.js.map and complains about it.

**A workaround is to compile with the -b option. Let me know it this indeed does the trick for you.**

A definitive solution is a bit more involved, since this flaw holds for all 'extra' files, e.g. also for the parsetree generated with -dt.
One possibility would be to automatically force a complete build if any debugging switches are involved, but this is rather ugly.
 A neater way would be to check those extra files. They should exist and be newer than the source. If not, that module has to be recompiled.

I'll keep you both informed on progress.

**Comment by JdeH** [comment] 2016-09-06 10:14
This should be fixed in 3.5.220, using the 'neater way'.
Let me know if it works for you.

@ihph & @ miguelgrinberg: Many thanks for reporting this issue. The quality of Transcrypt really depends on feedback like this. Took a while before I could reproduce it, since I habitually use the -b switch. I do that because often the compiler rather than the source files are changed and I need to force recompilation to test the new features...

Kind regards
Jacques

**Comment by miguelgrinberg** [comment] 2016-09-06 22:23
@JdeH Thanks. Adding `-b` does fix the issue for me.

**Comment by JdeH** [comment] 2016-09-07 05:33
Hi

I've commtted 3.5.220 which should have fised it all together, also without the -b switch. I wil (re)generate only those files necessary, including the maps.

KR
Jacques

**Closed** 2016-09-10 07:09 UTC
Labels: bug

**Comment by miguelgrinberg** [comment] 2016-09-10 17:08
Thanks!
